#!/bin/bash

function allcommands {
  echo -e '\033[32m./run                  \033[37;2m режим разработки на сервере http://localhost:4000/\033[0m'
  echo ''
  echo -e '\033[32m./run post "Заголовок" \033[37;2m написание нового поста\033[0m'
  echo ''
  echo -e '\033[32m./run upd              \033[37;2m обновить стили шаблона\033[0m'
  echo ''
  echo -e '\033[32m./run deploy           \033[37;2m опубликовать текущую версию блога\033[0m'
  echo ''
  echo -e '\033[32m./run help             \033[37;2m перечень доступных команд\033[0m'
}

function helpcmd {
  echo ''
  echo ''
  echo 'При редактировании записей блога доступны следующие команды:'
  echo ''
  allcommands
  echo ''
  echo ''
}

function unknowncmd {
  echo ''
  echo ''
  echo -e 'Хм... Любопытный параметр -- \033[35m'$1'\033[0m.'
  echo 'Но ты лучше выбери одну из доступных команд:'
  echo ''
  allcommands
  echo ''
  echo ''
}

if [[ $# -eq 0 ]]; then
  rake generate
  echo ''
  echo ''
  echo -e '\033[32mБлог доступен по адресу http://localhost:4000/\033[0m'
  echo ''
  echo ''
  open http://localhost:4000/
  rake preview
else
  case $1 in
    post) subl $(rake new_post["$2"] | cut -c 20-);;
    deploy) rake generate && rake deploy;;
    upd) rake generate;;
    help) helpcmd;;
    *) unknowncmd $1;;
  esac
fi